---
apiVersion: v1
kind: Pod
metadata:
  name: demo
  labels:
    app: demo
    run: demo
spec:
  containers:
  - name: http
    image: mardukay/demo:v1.0.0
    ports:
    - containerPort: 8080